// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eakluiyhqhydhjsdekho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVha2x1aXlocWh5ZGhqc2Rla2hvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NzQ4OTUsImV4cCI6MjA1OTQ1MDg5NX0.MFJm1aCuExW9CfeS-Ajo-iS_z05ueYfpYdL0UcvSl9U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);